name: hive_bloc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  hive: 2.0.5
  hive_flutter: 1.1.0
  flutter_bloc: 8.0.1
  equatable: 2.0.3
  hive_generator: ^1.1.1
  build_runner: ^2.1.7
  path_provider: 2.0.8
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

